# Perceptron_and

In [1]:
import numpy as np
from Perceptron import Perceptron

if __name__ == '__main__':
    X = np.array([[0,0],[0,1],[1,0],[1,1]])
    y = np.array([-1,-1,-1,1])
    
    ppn = Perceptron(eta=0.01)
    ppn.fit(X,y)
    print(ppn.errors_)

[0.02 0.02 0.02]
[0.   0.04 0.02]
[-0.02  0.04  0.02]
[-0.02  0.04  0.04]
[-0.04  0.04  0.02]
[-0.04  0.04  0.02]
[-0.04  0.04  0.02]
[-0.04  0.04  0.02]
[-0.04  0.04  0.02]
[-0.04  0.04  0.02]
[1, 3, 3, 2, 1, 0, 0, 0, 0, 0]


In [ ]:
# 5번째 이후로 가중치의 업데이트가 발생하지 않으므로 학습이 완료 되었다.